import {
  createStoreTier,
  createTierPerk,
  createStoreTemplate,
  createStoreCategory,
  getStoreTiers,
  getTierWithPerks,
  getStoreCategories,
  deleteStoreCategory,
  getStoreTemplates,
  getAllStores,
  getStoresWithFilters,
  getStoreById,
  updateStoreStatus,
  bulkUpdateStoreStatus,
  updateStoreExtraDetails,
  addStoreBanner,
  deleteStoreBanner,
  getStoreStatistics,
  getPendingStores,
  searchStores,
  deleteStore,
  updateStoreTier,
  getStoresByUser,
} from "./handlers/store";
import {
  getAllKyc,
  getKycById,
  getPendingKyc,
  getKycWithUserDetails,
  approveKyc,
  rejectKyc,
  updateKycIdentificationStatus,
  getKycStatistics,
  getKycByUserId,
  getAllBvn,
  approveBvn,
  rejectBvn,
} from "./handlers/kyc";
import {
  getAllUsers,
  getUserById,
  updateUserRole,
  updateUserVerification,
  updateUserProfile,
  getUsersByRole,
  getUserStatistics,
  getRecentUsers,
  getUsersWithStores,
  updateUserStoreStatus,
  searchUsers,
} from "./handlers/users";

export const adminRouter = {
  store: {
    getAllStores,
    getStoresWithFilters,
    getStoreById,
    getPendingStores,
    searchStores,
    updateStoreStatus,
    bulkUpdateStoreStatus,
    deleteStore,
    updateStoreTier,
    getStoresByUser,
    getStoreStatistics,

    updateStoreExtraDetails,

    addStoreBanner,
    deleteStoreBanner,

    tier: {
      getStoreTiers,
      createStoreTier,
      createTierPerk,
      getTierWithPerks,
    },
    template: {
      createStoreTemplate,
      getStoreTemplates,
    },
    category: {
      createStoreCategory,
      getStoreCategories,
      deleteStoreCategory,
    },
  },
  kyc: {
    getAllKyc,
    getKycById,
    getPendingKyc,
    getKycWithUserDetails,
    getKycByUserId,
    approveKyc,
    rejectKyc,
    updateKycIdentificationStatus,
    getKycStatistics,

    bvn: {
      getAllBvn,
      approveBvn,
      rejectBvn,
    },
  },
  users: {
    getAllUsers,
    getUserById,
    getUsersByRole,
    getUserStatistics,
    getRecentUsers,
    getUsersWithStores,
    searchUsers,

    updateUserRole,
    updateUserVerification,
    updateUserProfile,
    updateUserStoreStatus,
  },
};
